// <auto-generated />
using ABCIncAPI_991690389.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ABCIncAPI_991690389.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    partial class EmployeeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("ABCIncAPI_991690389.Models.EmployeeDM", b =>
                {
                    b.Property<int>("eId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("eDependentCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("eEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("eEmploymentType")
                        .HasColumnType("TEXT");

                    b.Property<string>("eName")
                        .HasColumnType("TEXT");

                    b.Property<int>("eSalary")
                        .HasColumnType("INTEGER");

                    b.HasKey("eId");

                    b.ToTable("EmployeeInfo");
                });

            modelBuilder.Entity("ABCIncAPI_991690389.Models.StudentDM", b =>
                {
                    b.Property<int>("StudentNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("StudentNumber");

                    b.ToTable("students");
                });
#pragma warning restore 612, 618
        }
    }
}
